
# -*- mode: python ; coding: utf-8 -*-
from PyInstaller.utils.hooks import collect_all

datas = []
binaries = []
hiddenimports = []
tmp_ret = collect_all('rich')
datas += tmp_ret[0]; binaries += tmp_ret[1]; hiddenimports += tmp_ret[2]

block_cipher = None

# 主应用分析
a = Analysis(
    ['start_unified.py'],
    pathex=['/Users/liu/data/python/CapsWriter-Offline'],
    binaries=binaries,
    datas=datas + [
        ('assets', 'assets'),
        ('util', 'util'),
        ('agent', 'agent'),
        ('config_example.toml', '.'),
        ('config.toml', '.'),
        ('hot-*.txt', '.'),
        ('keywords.txt', '.'),
        ('README_UNIFIED_LAUNCHER.md', '.'),
        ('readme.md', '.'),
        ('requirements*.txt', '.'),
    ],
    hiddenimports=hiddenimports + [
        'PySide6.QtCore',
        'PySide6.QtWidgets', 
        'PySide6.QtGui',
        'PySide6.QtSvg',
        'websockets',
        'sounddevice',
        'numpy',
        'requests',
        'json',
        'asyncio',
        'threading',
        'multiprocessing',
        'signal',
        'pathlib',
        'argparse',
        'subprocess',
        'sys',
        'os',
        'time',
        'datetime',
        'logging',
        'traceback',
        'queue',
        'collections',
        'functools',
        'itertools',
        'contextlib',
        'weakref',
        'copy',
        'pickle',
        'base64',
        'hashlib',
        'hmac',
        'uuid',
        'random',
        'math',
        'statistics',
        're',
        'string',
        'textwrap',
        'unicodedata',
        'locale',
        'gettext',
        'calendar',
        'email',
        'mimetypes',
        'urllib',
        'http',
        'ftplib',
        'poplib',
        'imaplib',
        'smtplib',
        'socketserver',
        'xmlrpc',
        'xml',
        'html',
        'csv',
        'configparser',
        'fileinput',
        'glob',
        'fnmatch',
        'linecache',
        'tempfile',
        'gzip',
        'bz2',
        'lzma',
        'zipfile',
        'tarfile',
        'mlx',
        'mlx.core',
        'mlx.nn',
        'mlx_lm',
        'mlx_lm.models',
        'mlx_lm.utils',
        'mlx_lm.sample_utils',
        'mlx_lm.tokenizer_utils',
        'rich',
        'rich.console',
        'rich.live',
        'rich.panel',
        'rich.markdown',
        'rich.text',
        'rich.progress',
        'rich.table',
        'rich.logging',
        'rich.style',
        'rich.theme',
        'rich.syntax',
        'rich.align',
        'rich.box',
        'rich.padding',
        'rich._unicode_data',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='CapsWriter-Offline',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=True,  # 设置为终端应用
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon='assets/appicon.ico',
)

coll = COLLECT(
    exe,
    a.binaries,
    a.zipfiles,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name='CapsWriter-Offline',
)

app = BUNDLE(
    coll,
    name='CapsWriter-Offline.app',
    icon=None,  # 暂时移除图标以避免格式问题
    bundle_identifier='com.capswriter.offline',
    version='1.0.3',
    info_plist={
        'CFBundleName': 'CapsWriter-Offline',
        'CFBundleDisplayName': 'CapsWriter离线版',
        'CFBundleVersion': '1.0.3',
        'CFBundleShortVersionString': '1.0.3',
        'CFBundleIdentifier': 'com.capswriter.offline',
        'CFBundleExecutable': 'CapsWriter-Offline',
        # 'CFBundleIconFile': 'appicon.ico',  # 暂时注释掉图标文件
        'CFBundlePackageType': 'APPL',
        'CFBundleSignature': 'CWOF',
        'LSMinimumSystemVersion': '10.13.0',
        'NSHighResolutionCapable': True,
        'NSRequiresAquaSystemAppearance': False,
        'LSUIElement': False,  # 设置为普通应用，在 Dock 中显示
        'NSMicrophoneUsageDescription': 'CapsWriter需要访问麦克风进行语音识别',
        'NSAppleEventsUsageDescription': 'CapsWriter需要发送Apple Events来控制其他应用程序',
        'NSSystemAdministrationUsageDescription': 'CapsWriter需要系统管理权限来监控键盘输入',
    },
)
